### ISSUE TITLE
CTRL+C ne fonctionne pas comme prévu

### ISSUE THREAD

**Issue by yolopix-dotfledge** [Asia81/HackingToolkit9DS#11]
CTRL+C (terminer le programme batch) ramène à des endroits différents du programme au lieu de quitter complètement si la touche est appuyée plusieurs fois.

**Comment by Asia81** [comment]
Pas sûr de comprendre ?
Pourquiter, tu le ferme juste après la croix rouge, comme chaque programme Windows ?

**Comment by yolopix-dotfledge** [comment]
Ouais je sais bien mais par habitude j'utilise CTRL+C pour terminer une action en cours, donc si quelqu'un a la même habitude et fait pareil, ça "casse" le fonctionnement du programme.
Après c'est pas un bug très grave, tu devrais juste rajouter un petit goto :eof à la fin de chaque "écran".

**Comment by Asia81** [comment]
Bah j'ai testé CTRL+C et ca fonctionne chez moi, ca ferme bien le programme (je connaissais même pas ce raccourcis (qui n'en est même pas un, c'est bien plus rapide de ferme avec la croix)). Donc je voius pas trop le soucis en fait.

**Comment by yolopix-dotfledge** [comment]
C'est étonnant. Si ça fonctionne chez toi ça doit venir de mon côté alors.
Sinon CTRL+C est utile pour arrêter les tâches en cours (quand une extraction est bloquée par exemple) et que la croix ne fait que cacher l'invite de commandes.
Si tu n'as rien d'autre à ajouter tu peux fermer l'issue, je voudrais pas te déranger pour un programme qui bug juste sur mon pc.

**Comment by Asia81** [comment]
CTRL+C, o pour Oui et ca à bien fermer, j'ai pas eu de soucis, bizarre :/
http://image.noelshack.com/fichiers/2017/42/5/1508519863-01.png
