### ISSUE TITLE
Setup file not there

### ISSUE THREAD

**Issue by XxrickybobbyxX** [Asia81/HackingToolkit9DS#12]
am i missing something, or is there no setup file?

**Comment by cooltrainergavin** [comment]
I'm having the same issue. It's nowhere to be found. I downloaded the source code file of v11 and it's not there in either the English or French folder.

**Comment by XxrickybobbyxX** [comment]
ok, at least I'm not going crazy.

**Comment by Asia81** [comment]
Setup is in the release pack.
IF you used the source, you don't need the setup pack, all programs are in your work folder.
Open the HackingToolkit9DS.bat file in Notepad++ and cut these first lines

> IF EXIST "%PROGRAMFILES%\HackingToolkit9DS\*.*" GOTO TitleMenu
> IF NOT EXIST "%PROGRAMFILES%\HackingToolkit9DS\*.*" GOTO NoInstalledSetup
> 
> :NoInstalledSetup
> echo set WshShell = WScript.CreateObject("WScript.Shell") > %tmp%\tmp.vbs
> echo WScript.Quit (WshShell.Popup( "Hey, it seems like you didn't install the SetupUS.exe file.			Please do it in order to use this tool, thanks!",0 ,"No Installed Setup",0)) >> %tmp%\tmp.vbs
> cscript /nologo %tmp%\tmp.vbs
> del %tmp%\tmp.vbs
> goto:eof

**Comment by SnoillerFitzroy** [comment]
So how do I find this "set up" executable, for those of us who DO need it?
