### ISSUE TITLE
Titles like PictoChat.cia does not gets installed while extractor says its succed.

### ISSUE THREAD

**Issue by LAMGE2** [Asia81/HackingToolkit9DS#18]
So, I downloaded PictoChat.cia for 3DS and wanted to make it 3DS extension so it may work at my emulator. But, as we can see it says succed and none of the folders exits like ExtractedExeFS

**Comment by torin555** [comment]
First of all, you can't convert a .cia file to a .3ds file. If that's all you want to do, you'll need to find a .3ds file somewhere. Second of all, make sure the .cia file is not decrypted if you're using V11. If the .cia file is decrypted you need to use V9. Either way, you can't convert it to a .3ds file.

**Comment by Asia81** [comment]
> First of all, you can't convert a .cia file to a .3ds file
makerom.exe -ciatocci OutputRom.3ds
