### ISSUE TITLE
Does not extract or reconstruct

### ISSUE THREAD

**Issue by MiqellDestroyer** [Asia81/HackingToolkit9DS#5]
When I extract the cia it does not extract the folders
[Image](http://i.imgur.com/qNNDPXA.png)

**Comment by Asia81** [comment]
Do you still have the issue?

**Comment by MiqellDestroyer** [comment]
yep

**Comment by MiqellDestroyer** [comment]
Nop
:dancer:

**Comment by Filo97** [comment]
I do

**Comment by Asia81** [comment]
I'm working for a fix with boot9 keys, it work but not properly.
You have to wait a bit
